# Generated by Django 3.2.7 on 2021-09-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='username1', max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('response', models.TextField(max_length=500)),
            ],
        ),
    ]
